apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
leaderElection:
  leaderElect: false
clientConnection:
  kubeconfig: "/home/achref/.kube/config"
profiles:
  - schedulerName: network-aware-scheduler
    plugins:
      multiPoint:
        enabled:
          - name: NetworkOverhead
            weight: 5 # A higher weight is given to NetworkOverhead to favor allocation schemes with lower latency.
          - name: BalancedAllocation
            weight: 1
        disabled:
          - name: NodeResourcesFit # Preferably avoid the combination of NodeResourcesFit with NetworkOverhead
      queueSort:
        enabled:
          - name: TopologicalSort
        disabled:
          - name: "*"
    pluginConfig:
      - name: TopologicalSort
        args:
          namespaces:
            - "default"
      - name: NetworkOverhead
        args:
          namespaces:
            - "default"
          weightsName: "UserDefined" # The respective weights to consider in the plugins
          networkTopologyName: "net-topology-test" # networkTopology CR to be used by the plugins

