kind: Deployment
apiVersion: apps/v1
metadata:
  name: appgroup-controller
  namespace: network-aware-controllers
  labels:
    app: appgroup-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appgroup-controller
  template:
    metadata:
      labels:
        app: appgroup-controller
    spec:
      serviceAccountName: appgroup-controller
      containers:
      - name: appgroup-controller
        image: localhost:5000/appgroup-controller/controller:latest
        command:
        - /bin/controller
        imagePullPolicy: IfNotPresent
